### ISSUE TITLE
Error when starting file server

### ISSUE THREAD

**Issue by feenr** [pegasystems/tracer-client#29]
This error is caused by some dependency clean up I did a couple weeks back.

```
> node express-mock-tracer-servlet

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'cors'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/feenr/workspaces/tracer-client/dev-tools/express-mock-tracer-servlet.js:6:14)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by feenr** [comment]
I was wrong. Ignore this.
